##
## =====================================================================================
##  C O P Y R I G H T
## -------------------------------------------------------------------------------------
##  Copyright (c) 2022 by Robert Bosch GmbH. All rights reserved.
##
##  Author(s):
##  - Markus Braun, :em engineering methods AG (contracted by Robert Bosch GmbH)
## =====================================================================================
##

name: "Ensure Poetry is set up"
description: "Installs python and poetry if necessary"
inputs:
  python-version:
    description: "The version of python to use (default: 3.9)"
    required: true
    default: 3.9
runs:
  using: "composite"
  steps:
  - name: "setup python"
    id: setup-python
    uses: actions/setup-python@v2
    with:
      python-version: ${{ inputs.python-version }}
  - name: "setup poetry"
    uses: snok/install-poetry@v1
    with:
      virtualenvs-create: true
      virtualenvs-in-project: true
      installer-parallel: true
  - name: "install dependencies"
    run: |
      poetry install
    shell: bash
