##
## =====================================================================================
##  C O P Y R I G H T
## -------------------------------------------------------------------------------------
##  Copyright (c) 2023 by Robert Bosch GmbH. All rights reserved.
##
##  Author(s):
##  - Markus Braun, :em engineering methods AG (contracted by Robert Bosch GmbH)
## =====================================================================================
##

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write



jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - name: "Checkout Code"
      uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 0
    
    - name: "Ensure Python/Build Environment v${{ matrix.python-version }}"
      uses: ./.github/actions/init
      with:
        python-version: ${{ matrix.python-version }}

    - name: "Run Tests"
      run: |
        mkdir -p docs/doxygen
        poetry run pytest --emoji -v -s --md $GITHUB_STEP_SUMMARY

  qa:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout Code"
      uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 0

    - name: "Ensure Python/Build Environment"
      uses: ./.github/actions/init
      with:
        python-version: "3.12" 

    - name: "cache pre-commit"
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-py3.12-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          ${{ runner.os }}-py3.12

    - name: "Run quality checks"
      run: |
        SKIP=poetry-lock poetry run pre-commit run --all-files

  release:
    runs-on: ubuntu-latest
    needs: [test, qa]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):')

    steps:
    - name: "Checkout Code"
      uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 0

    - name: "Ensure Python/Build Environment"
      uses: ./.github/actions/init
      with:
        python-version: "3.12"

    - name: "Update version, changelog"
      id: versionbump
      run: |
        git config user.email "actions@github.com"
        git config user.name "github-actions"
        poetry run cz bump --changelog
        git push
        git push --tags
        export VERSION=$(poetry version -s)
        poetry run cz changelog --dry-run $VERSION
        poetry run cz changelog --file-name RELEASE_NOTES.md $VERSION
        echo "::set-output name=new_version_tag::v$VERSION"
        git switch --detach v$VERSION
      env:
        GH_TOKEN: ${{ secrets.GITHUBTOKEN }}

    - name: "Create Release (will be filled in cd)"
      uses: softprops/action-gh-release@v1
      with:
        body_path: RELEASE_NOTES.md
        tag_name: ${{ steps.versionbump.outputs.new_version_tag }}
        token: ${{ secrets.GITHUBTOKEN }}
