##
## =====================================================================================
##  C O P Y R I G H T
## -------------------------------------------------------------------------------------
##  Copyright (c) 2023 by Robert Bosch GmbH. All rights reserved.
##
##  Author(s):
##  - Stefan Schulz, Robert Bosch GmbH
## =====================================================================================
##

name: Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

strategy:
  matrix:
    python-version: ["3.9", "3.10", "3.11", "3.12"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout Code"
      uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 0

    - name: "Ensure Python/Build Environment v${{ matrix.python-version }}"
      uses: ./.github/actions/init
      with:
        python-version: ${{ matrix.python-version }}

    - name: "Run Tests"
      run: |
        mkdir -p docs/doxygen
        poetry run pytest --emoji -v -s --md $GITHUB_STEP_SUMMARY
