##
## =====================================================================================
##  C O P Y R I G H T
## -------------------------------------------------------------------------------------
##  Copyright (c) 2022 by Robert Bosch GmbH. All rights reserved.
##
##  Author(s):
##  - Markus Braun, :em engineering methods AG (contracted by Robert Bosch GmbH)
## =====================================================================================
##

name: "Tools: repair dpkg"

on:
  workflow_dispatch:

jobs:
  tools-dpkgrepair:
    runs-on: self-hosted
    steps:
      - name: "repair: dpkg"
        run: |
          echo "Attempting to fix dpkg..."
          sudo dpkg --configure -a
